version: '3.8'
services:
  app:
    container_name: express_app
    build: .
    ports:
      - "4444:4444"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
